name: nightly

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    defaults:
        run:
          shell: bash
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: ./.github/scripts/req.sh
    - name: Build packages
      run: |
        wget -q --no-check-certificate https://github.com/MiscPS3/NixSDK/releases/download/2023.09.17/bullseye-sdk.tar.gz -O psdk.tar.gz
        tar -C /usr/local/ -xzf psdk.tar.gz
        . ./.github/scripts/env.sh
        export CSHA=${GITHUB_SHA:0:7}
        export TAIL="Nightly_${CSHA}"
        make pkg VERBOSE=1 V=1
        export TAGGY="nightly_${CSHA}" && ./.github/scripts/name.sh
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          tag_name: pkg-${{ github.sha }}
          name: pkg-${{ github.sha }}
          prerelease: false
          files: *.pkg
